language: go
go:
- '1.14'
env:
  global:
  - GO111MODULE=on
go_import_path: github.com/aaharu/agif
before_script:
- nvm install 12.16.2
- nvm use 12.16.2
- npm i -g yarn
- yarn
script:
- go test -v ./...
- yarn build
deploy:
  provider: heroku
  api_key:
    secure: SqoZBFRiI91xssynoW6CA+nr2MxXsru+jtQHpX/qeqF7UYOysEI6tfLRtS74JENVYI58UuxZAuEtGm9xGL9q5y7hnW+zb4vWNODK30qmuPKcYnmeAAvcrqeYvuAWrbkAipVG7UP6YxkIxcQiYw/ld6/Q1/fTsTCzhUMEDn9CMJ0=
  skip_cleanup: true
  app: agif
  on:
    repo: aaharu/agif
branches:
  only:
  - master
