language: go
go:
  - '1.14'
env:
  global:
    - GO111MODULE=on
go_import_path: github.com/aaharu/agif
before_script:
  - nvm install 12.16.2
  - nvm use 12.16.2
  - npm i -g yarn
  - yarn
script:
  - go test -v ./...
  - yarn build
deploy:
  provider: heroku
  api_key:
    secure: CWf6swnMjPZv+k+KBbrLQX7djEtc6Xugay3zWFhkbPD0oqddW7VWAmng7l5qvmeComOsZxOA02S8N80EBvd5Zu2oCEzj1mb03MNZ/355YjTgexbUt2oGq+ZHwFfdYCgv33kNhKVnV5oPf1ZrY1AWOKzIU1dS7cKaMa9jQlzb/wk=
  skip_cleanup: true
  app: agif
  on:
    repo: aaharu/agif
branches:
  only:
    - master
