language: go
go:
  - '1.12'
env:
  global:
    - GO111MODULE=on
go_import_path: github.com/aaharu/agif
before_script:
  - npm i -g npm
  - npm ci
script:
  - go test -v ./...
  - npm run build
deploy:
  provider: heroku
  api_key:
    secure: ${APIKEY}
  app: agif
  on:
    repo: aaharu/agif
branches:
  only:
    - master
